export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCH_PRODUCTS_ARR = "FETCH_PRODUCTS_ARR";
// categories types
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CATEGORY = "FETCH_CATEGORY";
